### ISSUE TITLE
It would be perfect if elm-tiptap could be insert a video

### ISSUE THREAD

**Issue by UILKUNP** [Leecason/element-tiptap#1]
It would be perfect if elm-tiptap could be insert a video👍🏿👍🏿👍🏿

**Comment by Leecason** [comment]
simple implementation with release v1.4.0
see https://leecason.github.io/element-tiptap/#/embed

**Comment by elva2596** [comment]
> simple implementation with release v1.4.0 see https://leecason.github.io/element-tiptap/#/embed

the link is invalid
