### ISSUE TITLE
Need more explanation regarding custom plugin

### ISSUE THREAD

**Issue by neelay92** [Leecason/element-tiptap#10]
How do I create custom extension, say for Heading?
In the doc it is mentioned to extend the Base Class, but what if I want to add a custom class to it?
Is it similar to tiptap, wherein the we need to define it in the schema/doc?

Also can you explain what menuBtnView (editorContext) {} expects and needs to return.

Thanks. 
Great work on the plugin!

**Comment by Leecason** [comment]
I created this simple demo for you. you can check it

[**Create The Custom Bold Menu Button**](https://codesandbox.io/s/create-custom-extension-with-menu-button-y3mp4)

In your custom extension class, add a `menuBtnView` function to return a object (in there i called `Vue Component Spec`) that contains three attribute:

```js
{
  component:  // your vue component
  componentProps: {
    // props will pass to your vue component
  },
  componentEvents: {
    // handle events that your component emit
  },
}
```

`menuBtnView` function has just one param `editorContext`, its properties are same as [https://github.com/scrumpy/tiptap#editormenubar](https://github.com/scrumpy/tiptap#editormenubar), i just plus [the tiptap editor instance](https://tiptap.scrumpy.io/docs/guide/editor.html) to it.

Also you can overwrite such as schema, plugins and commands in your custom extension class like in tiptap. [create-custom-extensions](https://github.com/scrumpy/tiptap#create-custom-extensions)

If you want to render multiple buttons in one extension, just like you say the **Heading** extension.

your can return a `Vue Component Spec` array in the `menuBtnView`:

```js
class Bold extends OriginalBold {
  menuBtnView () {
    return [
       {
          component: componentH1,
       },
       {
          component: componentH2,
       }
      ...
    ];
  }
}
```

I'm glad to reply if you have any other questions.
thanks for supporting this project.

**Comment by Leecason** [comment]
Do you still have any questions?

**Comment by neelay92** [comment]
Hey
Thanks for the reply. I managed to get it working by your help.

**Comment by shadrachtuck** [comment]
@Leecason Trying to render multiple buttons in the extension as per your last example works for rendering buttons but the logic within component events is not firing. Perhaps I have the syntax incorrect??
```
export default class Bold extends OriginalBold {
  // here you can extend the extension like tiptap, such as schema, plugins ...
  menuBtnView({ isActive, word, code }) {
    
    return [
        {
          component: RhymeButton,
        },
        {
          component: ThesaurusButton,
        },
        {
          component: DictionaryButton
        },
      {
      componentProps: {
        isActive: isActive.bold(),
        word: String,
        code: String
      },
      props: ["code"],
      componentEvents: {
        click: () => {
          let word = this.word;
          word = (document.all)
          ? document.selection.createRange().text.toString()
          : document.getSelection().toString().trim().toLowerCase();
          // document.getElementById('hidden').value = word;
          // document.onmouseup = getSelectionText;
          // if (!document.all) document.captureEvents(Event.MOUSEUP);
          this.word = word;
          store.commit("addWord", this.word)
        },
      },
    }
    
    ];

  }

}

```

**Comment by Leecason** [comment]
@shadrachtuck 
Each component object contains its props and events

```js
menuBtnView (editorContext) {
  return [
    {
      component: compA,
      componentProps: compAprops,
      componentEvents: compAevents, 
    },
    {
      component: compB,
      componentProps: compBprops,
      componentEvents: compBevents,
    },
    ...
  ],
}
```

**Comment by shadrachtuck** [comment]
@Leecason oh of course! brilliant, thank you!

**Comment by meiguiyisenluo** [comment]
你好，这个有用，实在太好了，但是在控制台上log(context.commands)时，一些方法是有个attr参数的，在tiptap 文档上没找到对应的commands，例如context.commands.heading，我应该在哪里能找到这个attr的传参呢
