### ISSUE TITLE
Best approach for loading new Doc back into Editor

### ISSUE THREAD

**Issue by shadrachtuck** [Leecason/element-tiptap#111]
Hey Lee, 

First of all, great work on this plug-in! It's made my job a hell of a lot easier over recent months. I appreciate you adding my feature request as well. 

Anyway, I have a quick question about loading data back into the editor... I am able to retrieve it and successfully load it into the editor. However, I am mutating the prop directly by using `this.content = recentDoc` within my setter function. I know this is a bad pattern, and I fear it's now refreshing the editor state either. I have looked into the TipTap documentation on the matter and it appears people are doing this with `this.editor.setContent(content)` but I realize these methods aren't available with el-tiptap.  I was looking into the Prosemirror props such as `content, emitUpdate, parseOptions` but I am unclear about how/where to implement them.

Maybe you could steer me in the right direction? 

Let me know, thanks!

Shad

**Comment by Leecason** [comment]
```html
<el-tiptap v-model="content"></el-tiptap>
```

You can use `v-model` to bind `content` then you can update content in your app or

template:

```html
<el-tiptap @onInit="onInit"></el-tiptap>
```

js:

```js
onInit({ editor }) {
  // you can access to `editor`, then you can editor.setContent(yourContent).
}
```

**Comment by shadrachtuck** [comment]
Awesome! Thank you so much for the quick reply! That was the clarification that i needed.

**Comment by shadrachtuck** [comment]
Now the onInit({ editor }) {} function is returning editor as undefined. It only returns defined in creat() hook. Obviously though, that is not the place I need it as I need to call the function on demand and not automatically.

**Comment by Leecason** [comment]
I do this code sandbox for you 
https://codesandbox.io/s/element-tiptap-s5ysn?file=/src/components/Editor.vue
You can see the `editor` in console(you can ignore the warnings from `vue`)

**Comment by shadrachtuck** [comment]
@Leecason I never realized since implementing this and passing editor as a data object to later save to db (this.editor = editor), that it is slowing the performance of the editor waaay way down. I've tested in the sandbox as well and I'm getting the issues about multiple versions of prosemirror being loaded but not performance issues. Any issues on your side with performance when using onInit?

**Comment by Leecason** [comment]
I'm not sure if this performance issue is related to the editor. Could you provide more codes or an online demo?

**Comment by shadrachtuck** [comment]
https://codesandbox.io/s/element-tiptap-x101r?file=/src/components/Editor.vue

This demo isn't providing the same lag it was for me. However, I am running vue in electron and have other factors in the project. This demo is about as stripped-down as it gets. I solved the issue with a workaround, however it seems for me that onInit keeps sending event updates and loading a new version of the editor event while the document is edited.
