### ISSUE TITLE
If only using bubble menu and you set a link, you lose access to text bubble menu

### ISSUE THREAD

**Issue by justanotherco** [Leecason/element-tiptap#117]
If you only use Bubble menu and all the contents has one link. It isn't possible to see the text bubble menu anymore.

I am using tiptap on a "button" so the entire text in the button will always be a link.

If you go to this sandbox, try to make it Italic:

https://codesandbox.io/s/element-tiptap-88tsp

The only 2 ways a user can do it are:
1- Type more text that isn't part of the link then select all text, apply Italic, delete the extra text you added
2- Remove link using unlink tool, select all text, apply italic and then re-add link again to text

But both of those are really bad for user experience. 

The best solution would be for an extra button in the Link bubble menu (with a back arrow "<-" or similar), that when clicked hides the link bubble menu and shows the normal text bubble menu.

Is something like this at all possible?

Thank you very much.

**Comment by justanotherco** [comment]
Ah I just realized forking the sandbox doesn't save it. Please change the editor.vue file to this to see the issue:

`<template>
  <el-tiptap :extensions="extensions" :content="content" placeholder="Write something ..."/>
</template>

<script>
import {
  Doc,
  Text,
  Paragraph,
  Italic,
  Link,
} from "element-tiptap";

export default {
  name: "Editor",

  data: () => ({
    extensions: [
      new Doc(),
      new Text(),
      new Paragraph(),
      new Italic({ bubble: true, menubar: false }),
      new Link({ bubble: true, menubar: false }),
    ],

    content: `<a href="test.com">All text is link</a>`
  })
};
</script>
`

**Comment by Leecason** [comment]
This is a special case, I did not consider before. I will think about it. Thank you
