### ISSUE TITLE
Bubble Menu is cut off behind editor perimeter

### ISSUE THREAD

**Issue by isv9** [Leecason/element-tiptap#118]
Hi, I have trouble with the bubble menu. It is cut off behind editor perimeter. I saw #98 and I use element-tiptap `v1.24.2` but the bubble menu is cut. The `editor-menu-bubble` component has a `keepInBounds` property and if I change `keep-in-bounds` on true in source element-tiptap the bubble menu won’t be cut. Can we add property `keep-in-bounds` or advise another solution? Thanks

<img width="677" alt="Снимок экрана 2020-06-17 в 16 40 55" src="https://user-images.githubusercontent.com/49920738/84909915-ed50ed00-b0be-11ea-860d-cf38bc1fec59.png">

**Comment by yoramdelangen** [comment]
I think this is related to #98

**Comment by Leecason** [comment]
I saw such a problem, will fix it.

**Comment by Leecason** [comment]
I remove the option `keep-in-bounds: false` in menu-bubble, and add `menuBubbleOptions` prop to config this.
This is a temporary fix, and I'll improve it with `popper.js` later.
