### ISSUE TITLE
Error on enter key

### ISSUE THREAD

**Issue by krumal** [Leecason/element-tiptap#129]
ENTER key not working (for example, when we add a new line to end), and we got error in the console:

ERROR:
index.es.js:322 Uncaught RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)
    at Function.bo.from (index.es.js:322)
    at gi.create (index.es.js:1950)
    at e.h.split (index.es.js:805)
    at Array.w (index.es.js:340)
    at index.es.js:599
    at T.<anonymous> (index.es.js:85)
    at index.es.js:3236
    at so.someProp (index.es.js:4680)
    at sr.keydown (index.es.js:3236)
    at HTMLDivElement.t.dom.addEventListener.t.eventHandlers.<computed> (index.es.js:3162)

**Comment by hqzh** [comment]
1.24.5依旧有这个问题

**Comment by hqzh** [comment]
> 🎉 This issue has been resolved in version 1.24.4 🎉
> 
> The release is available on:
> 
> * [GitHub release](https://github.com/Leecason/element-tiptap/releases/tag/%401.24.4)
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/element-tiptap/v/1.24.4)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

@Leecason 1.24.5依旧有这个问题

**Comment by Leecason** [comment]
I tried to lock the `prosemirror-model` in my package, but it failed. You must manually do what is written in the [solution](https://github.com/scrumpy/tiptap/issues/577) for your project.

**Comment by hqzh** [comment]
"@types/prosemirror-model": "^1.7.2",  你那个包是这个啊
