### ISSUE TITLE
Line-height working wrong

### ISSUE THREAD

**Issue by krumal** [Leecason/element-tiptap#146]
my default line-height project 1.3
.el-tiptap-editor__content {
  line-height: 1.3;
}

when i set line-height extension "105%" i get line-height: 178.5%;
when i save it and load value in v-model i get line-height on element 303.45%
element <p>

**Comment by Leecason** [comment]
Sorry, you can't just change `line-height` in CSS, I const the `line-height` to `1.7` in JS. For now, the value is a constant that is unable to be changed.

**Comment by krumal** [comment]
Ok, you can add it how parameter line-height extension?

But bug: "when i set line-height extension "105%" i get line-height: 178.5%;
when i save it and load value in v-model i get line-height on element 303.45%"?
when i load i see that my text more wider
