### ISSUE TITLE
custom menu

### ISSUE THREAD

**Issue by SinLiz** [Leecason/element-tiptap#157]
When customizing the menu button, how to pass the custom value to the custom menu button? Is there a more complete example of the custom menu?

I am not good at English, and I am using Google Translate. I really hope to get your answers.

**Comment by Leecason** [comment]
You can check this: https://github.com/Leecason/element-tiptap/issues/10

and a custom **Bold** button demo: https://codesandbox.io/s/create-custom-extension-with-menu-button-y3mp4

**Comment by SinLiz** [comment]
首先感谢你的回复.&nbsp; &nbsp; First of all thanks for your reply.
可能我没表达清楚我的问题.&nbsp; Maybe I didn’t express my question clearly.


上述例子中，如果我要在Editor.vue中将某个自定义的值传递到自定义菜单按钮中，我应该怎么传递并读取到这个值.
In the above example, if I want to pass a custom value to a custom menu button in Editor.vue, how should I pass and read this value?







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiaxun Li"<notifications@github.com&gt;; 
发送时间: 2020年7月28日(星期二) 上午10:28
收件人: "Leecason/element-tiptap"<element-tiptap@noreply.github.com&gt;; 
抄送: "张路"<243066208@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Leecason/element-tiptap] custom menu (#157)





 
You can check this: #10
 
and a custom Bold button demo: https://codesandbox.io/s/create-custom-extension-with-menu-button-y3mp4

**Comment by Leecason** [comment]
```js
menuBtnView (editorContext) {
  return {
    component: comp,
    componentProps: compProps,
    componentEvents: compEvents, 
   },
}
```

`editorContext` has many useful attributes, such as `isActive`, `commands`, and `editor` instance, you can get them and then pass to your component. check https://github.com/scrumpy/tiptap#editormenubar

**Comment by SinLiz** [comment]
> ```js
> menuBtnView (editorContext) {
>   return {
>     component: comp,
>     componentProps: compProps,
>     componentEvents: compEvents, 
>    },
> }
> ```
> 
> `editorContext` has many useful attributes, such as `isActive`, `commands`, and `editor` instance, you can get them and then pass to your component. check https://github.com/scrumpy/tiptap#editormenubar


![image](https://user-images.githubusercontent.com/25169848/88613663-8f9dc080-d0c0-11ea-9e29-417cef94521e.png)

I read the editorContext carefully, but it did not solve my problem. I customized a menu button for uploading attachments, and I want to pass this refId to my custom component (maybe my current new Appendix({ refId: this .refId}) is written incorrectly), I don’t understand how to read it through editorContext.

[我仔细看了 editorContext ，但是并没解决我的问题. 我自定义了一个附件上传的菜单按钮，我想把这个refId传递到我的自定义组件中（也许我现在的new Appendix({ refId: this.refId}) 写法不对），我没明白怎么通过editorContext去读取.]

**Comment by Leecason** [comment]
How about this demo: **A template text button** https://codesandbox.io/s/template-button-ctlmm

**Comment by SinLiz** [comment]
> How about this demo: **A template text button** https://codesandbox.io/s/template-button-ctlmm

This example is also passed in the MenuButton by calling the click method bound to componentEvents. I need to read the value in Editor.vue in MenuButton.vue or index.js.

In addition, I have a new question: How to define the Tooltip of the custom menu button?

这个例子也是在MenuButton中通过调用componentEvents绑定的click方法进行传递。我是需要在MenuButton.vue或者index.js中读取Editor.vue中的值。

另外，我还有一个新的问题：自定义菜单按钮的Tooltip怎么定义？

**Comment by SinLiz** [comment]
> > How about this demo: **A template text button** https://codesandbox.io/s/template-button-ctlmm
> 
> This example is also passed in the MenuButton by calling the click method bound to componentEvents. I need to read the value in Editor.vue in MenuButton.vue or index.js.
> 
> In addition, I have a new question: How to define the Tooltip of the custom menu button?
> 
> 这个例子也是在MenuButton中通过调用componentEvents绑定的click方法进行传递。我是需要在MenuButton.vue或者index.js中读取Editor.vue中的值。
> 
> 另外，我还有一个新的问题：自定义菜单按钮的Tooltip怎么定义？

Of course, I can read this value in other ways, such as vuex, which I don't want to do.
[当然，我可以通过别的方式去读取这个值，比如vuex，我并不想这么做。]

**Comment by SinLiz** [comment]
Sorry, it seems that I didn't take a closer look. The value transfer problem is solved.
Thank you very much for your patient answers..

**Comment by Leecason** [comment]
> > How about this demo: **A template text button** https://codesandbox.io/s/template-button-ctlmm
> 
> This example is also passed in the MenuButton by calling the click method bound to componentEvents. I need to read the value in Editor.vue in MenuButton.vue or index.js.
> 
> In addition, I have a new question: How to define the Tooltip of the custom menu button?
> 
> 这个例子也是在MenuButton中通过调用componentEvents绑定的click方法进行传递。我是需要在MenuButton.vue或者index.js中读取Editor.vue中的值。
> 
> 另外，我还有一个新的问题：自定义菜单按钮的Tooltip怎么定义？

You can get in click event, so you can pass it to your component

```js
export default class Template extends Extension {
  // here you can extend the extension like tiptap, such as schema, plugins ...
  get name() {
    return "template";
  }

  get defaultOptions() {
    return {
      text: "text from option"
    };
  }

  commands() {
    return text => (state, dispatch) => {
      let tr = state.tr.insertText(text);
      dispatch(tr);
      return true;
    };
  }

  menuBtnView({ isActive, commands, focus, editor }) {
    return {
      component: CustomBoldMenuButton,
      componentProps: {
         text: this.options.text, // here you can pass it to your component
      },
    };
  }
}

```

**Comment by SinLiz** [comment]
> 
> You can get in click event, so you can pass it to your component
> 
> ```js
> export default class Template extends Extension {
>   // here you can extend the extension like tiptap, such as schema, plugins ...
>   get name() {
>     return "template";
>   }
> 
>   get defaultOptions() {
>     return {
>       text: "text from option"
>     };
>   }
> 
>   commands() {
>     return text => (state, dispatch) => {
>       let tr = state.tr.insertText(text);
>       dispatch(tr);
>       return true;
>     };
>   }
> 
>   menuBtnView({ isActive, commands, focus, editor }) {
>     return {
>       component: CustomBoldMenuButton,
>       componentProps: {
>          text: this.options.text, // here you can pass it to your component
>       },
>     };
>   }
> }
> ```

I didn't see the example clearly just now. Sorry, this problem is solved, thank you.
So how should the "Tooltip" of the custom menu button be defined?
