### ISSUE TITLE
Help wanted to create pre-defined tables

### ISSUE THREAD

**Issue by shiwei2019** [Leecason/element-tiptap#172]
@Leecason and all buddies here, I am trying to create pre-defined tables as new nodes.  A pre-defined table has fixed rows X cols, headers, predefiend items for left-most column.  For example, a statistical table for physical checkup may look like this:
——————————————————————————
| Age group | Weight | Height | Blood Presure |
——————————————————————————
| 18-25   |     |     |        |
——————————————————————————
| 26-35   |     |     |        |
——————————————————————————
| 36-55   |     |     |        |
——————————————————————————

A user typing in a pre-defined command or select from menu,  then a template of this table will be shown and the user can input values into the cells.

I guess I can start from extending ProseMirror table.  I need help for the following,

1. How to pre-set the fixed number of rows X cols, and pre-set the headers and the text of the left-most column? and make them un-editable

2. Can I bind a data model to this node? Just like element-ui's el-table that using v-model to bind an data object to a table?

3. Can I define an event for a table cell? When a user types into a cell and leaves, an event handler will be called to process the value of this cell, similar to onBlur of element-ui?

Many thanks!

**Comment by Leecason** [comment]
Table is rendered by native tag `<table>`, not '<el-table>` component
