### ISSUE TITLE
[feature request] Option to change image alt attribute

### ISSUE THREAD

**Issue by leo1200** [Leecason/element-tiptap#21]
This would help me a lot;)

Thanks in advance

Leonard Storcks
from https://lernzettel.org/

**Comment by leo1200** [comment]
An easy way to add custom image processing would be great too, i. e. I´d like to upload the images to Google Cloud Storage. You could for instance provide a function that receives the image data and returns a custom source.

**Comment by Leecason** [comment]
Hi leo, thanks for your issue.

Recently I will improve the Image extension,  including your above features.

- support update alt attribute
- In the current version, you can pass `uploadRequest` to the Image extension when you instantiate it:

```ts
  new Image({
     uploadRequest (file: File): Promise<url> {
       // upload file to Google Cloud Storage

       return Promise.resolve(url); // return a Promise with your file source url
     },
  })
```

but now there is no uploading feedback, i will optimize it.

If you have any questions about this API, I will resolve it and deploy it with other image improvements.

**Comment by leo1200** [comment]
Thank you very very very much!!!!

**Comment by Leecason** [comment]
update image alt is available in version [1.17.0](https://github.com/Leecason/element-tiptap/releases/tag/%401.17.0)

**Comment by leo1200** [comment]
thanks 👍👍 element-tiptap will help me switch to an own little CMS solution for https://lernzettel.org/ :)

**Comment by leo1200** [comment]
[bug report] The image options are not visible in full-screen mode.

**Comment by leo1200** [comment]
And I am getting the following warning:
vue.runtime.esm.js?2b0e:619 [Vue warn]: Invalid prop: type check failed for prop "view". Expected EditorView, got Object 
found in
---> <ImageBubbleMenu>
       <ElPopover> at packages/popover/src/main.vue
         <ImageView>
           <EditorContent>
             <ElTiptap>
               <Anonymous>
                 <VContent>
                   <VApp>
                     <App> at src/App.vue
                       <Root>
Any ideas on this? Thanks :)

**Comment by Leecason** [comment]
> [bug report] The image options are not visible in full-screen mode.

Hey, i saw the problem and thought about it.
Using native fullscreen will just make **the element** fullscreen, but `element-ui` appends popover, tooltip etc. to the body, they're not in **this element**, so them not visible in fullscreen mode.
But if do not append them to the body, will also have rendering problems if the editor render in `el-dialog`.
So here I'm going to set `position: fixed` to the editor to make it **"fullscreen"** .
If you have a better suggestion, I would appreciate it very much.

**Comment by Leecason** [comment]
I have simply fixed these two problems and they are available now. 
I am still thinking about other better methods. 
If there are any other problems, welcome to submit an issue.
Thank you.
