### ISSUE TITLE
嵌套 dialog 组件 modal 显示异常

### ISSUE THREAD

**Issue by bdoycn** [Leecason/element-tiptap#22]
## 问题描述
版本: 1.15.0
问题: 在 dialog 组件中使用图片上传和预览组件的时候会出现遮罩层显示异常的问题
推断原因: dialog 组件没有使用 append-to-body 属性

## 截图
当期版本的表现
![no append-to-body](https://user-images.githubusercontent.com/31044988/77240895-3f03eb80-6c26-11ea-9c4a-b0cc2ec6cc44.png)

添加了 append-to-body 后的表现
![add append-to-body](https://user-images.githubusercontent.com/31044988/77240902-6064d780-6c26-11ea-8050-5a0d4a9bf664.png)

**Comment by Leecason** [comment]
thank you, bdoycn!
