### ISSUE TITLE
Module '"../node_modules/element-tiptap/lib"' has no exported member 'ElementTiptapPlugin'.

### ISSUE THREAD

**Issue by Lekkimone92** [Leecason/element-tiptap#234]
Hello, I'm using element-tiptap on a vue typescript project, everything is working, i can use the editor in my page but i'm facing an issue with the import of  'ElementTiptapPlugin'. I looked in the index.d.ts of lib directory but i haven't seen it in the export block. Need some help to get fit it.

![image](https://user-images.githubusercontent.com/37795298/95191038-77d56d80-07d0-11eb-9a9c-d756c4ea9e12.png)

**Comment by lxy1028900373** [comment]
请问是怎么解决的？我页面引入也会报错

**Comment by swuecho** [comment]
// @ts-ignore

即可
