### ISSUE TITLE
Add the typings for the project

### ISSUE THREAD

**Issue by tbhaxor** [Leecason/element-tiptap#257]
**Is your feature request related to a problem? Please describe.**
Due to the lack of typing, it is kinda headache for typescript developers
![image](https://user-images.githubusercontent.com/28386721/98938534-0cd53000-250e-11eb-8e31-ecf83960d429.png)

**Describe the solution you'd like**
Extend existing vue types and link it with the project.

**Comment by Moghul** [comment]
Agreed, I just tried to implement this in a vue-ts project and for the life of me I can't get it to work.

There are several issues:

The extension definitions are wrong, and don't take args despite the fact that they could:
![image](https://user-images.githubusercontent.com/17046245/181010883-486b38b6-7b46-4ee4-8047-d2b87d4af42a.png)

The actual plugin definition is broken. You've made it a type, so it can't be used as a value:
![image](https://user-images.githubusercontent.com/17046245/181010568-ec10e5b2-bc04-4bae-8935-a39a9b226f6f.png)
![image](https://user-images.githubusercontent.com/17046245/181010811-6181e67b-76a7-47ec-9fe6-de9b261281f8.png)
