### ISSUE TITLE
Unable to write in href field

### ISSUE THREAD

**Issue by tbhaxor** [Leecason/element-tiptap#260]
**Describe the bug**
Seems like the input for entering url is marked readonly

![image](https://user-images.githubusercontent.com/28386721/98940847-9c301280-2511-11eb-99ad-5bad0ace5ac1.png)

**To Reproduce**
1. Click on link extension

**Expected behavior**
It should be editable

**Screenshots**

![image](https://user-images.githubusercontent.com/28386721/98940691-5f641b80-2511-11eb-863b-00141a7464bf.png)

**Desktop (please complete the following information):**
+ OS: Linux
+ Browser: Chrome
+ Version: 86.0.4240.183

**Comment by Leecason** [comment]
There is no such setting which sets input readonly in my source code. What's your version of `element-ui` ?

**Comment by tbhaxor** [comment]
> What's your version of `element-ui` ?

element-ui@2.14.1

**Comment by Leecason** [comment]
Could you please provide a code sandbox?
