### ISSUE TITLE
It's not possible to add classes in code view (or other HTML attributes for that matter)

### ISSUE THREAD

**Issue by eudoxyz** [Leecason/element-tiptap#262]
If you have something like `<p>foo</p>`, and change it to `<p class="bar">foo</p>`, when you switch to WYSIWYG editor and then back to code view, you get `<p>foo</p>` again, i.e. the class gets discarded.

**Comment by Leecason** [comment]
Duplicated of https://github.com/Leecason/element-tiptap/issues/108
