### ISSUE TITLE
如何回显富文本编辑器内容和预览的效果一样

### ISSUE THREAD

**Issue by lxw6933** [Leecason/element-tiptap#292]
<div v-html="article.content"></div>回显富文本编辑器内容时，图片显示不了，样式也没有，

**Comment by jili20** [comment]
> 回显富文本编辑器内容时，图片显示不了，样式也没有，

我也遇到这个问题了, 我的部分样式失效, 如表格, 代码块, 请问这个问题你解决了吗?
