### ISSUE TITLE
New install `TypeError`

### ISSUE THREAD

**Issue by uwejan** [Leecason/element-tiptap#31]
HI, upon new install i get the following error.
`[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'spellcheck' of undefined"`
advice please?

**Comment by Leecason** [comment]
fixed in https://github.com/Leecason/element-tiptap/commit/8eb1e91c9eff3befee7111fc66a3df462ab06457

**Comment by uwejan** [comment]
@Leecason going to test it now.
is it possible to use it with bootstrap instead?

**Comment by Leecason** [comment]
you can customize menu button with bootstrap.
