### ISSUE TITLE
Nuxtjs下加粗、下划线、删除线、斜体出现“Failed to execute 'setStart' on 'Range……'”错误

### ISSUE THREAD

**Issue by yuxingxin** [Leecason/element-tiptap#310]
插件plugins/editor.js

```
import Vue from 'vue'
import { ElementTiptapPlugin } from 'element-tiptap';
import 'element-ui/lib/theme-chalk/index.css';
import 'element-tiptap/lib/index.css';

Vue.use(ElementTiptapPlugin, {
  lang: 'zh',
});
```

nuxt.config.js配置文件

```
plugins: [
     { src: '~/plugins/editor.js', ssr: false }
  ],
```

页面使用index.vue
```
<template>
      <client-only>
        <el-tiptap
          :extensions="extensions"
          :content="content"
          :spellcheck="false"
          :menu-bubble-options="{ 'keep-in-bounds': false }"
          @onInit="onInit"
          @onTransaction="onTransaction"
          placeholder="请输入正文内容..."
        />
      </client-only>
</template>
```
选中输入的内容，进行加粗，斜体等样式操作时，会出现以下错误
![image](https://user-images.githubusercontent.com/3411961/106852917-d1549700-66f3-11eb-905c-91199f9d30ef.png)

**Comment by muammersahin** [comment]
Hi,
The error is same in my code. I cannot fixed it. I solve the problem which causes content not change as;

   // onTransition
   fixEditor() {
      // This fixing is written for avoid tiptap plugin's range.setStart's offset error
      // It causes lack of data changing, we get the inner html and set to content as it is
      this.content = this.$refs.tiptapeditor.editor.view.docView.dom.innerHTML
    }

Waiting for fixing the issue.

Thanks

**Comment by zain5555** [comment]
@muammersahin did you find any fix for this?

**Comment by pablonunez-dev** [comment]
same error here,  any news or workaround ?

**Comment by yuxingxin** [comment]
更新tiptap版本到 1.32.2 可以解决此问题，详细查看：
https://github.com/ueberdosis/tiptap/issues/954
