### ISSUE TITLE
引入：import { ElementTiptap } from "element-tiptap";后控制台报错：Duplicate use of selection JSON ID cell

### ISSUE THREAD

**Issue by HEART-max** [Leecason/element-tiptap#375]
Uncaught RangeError: Duplicate use of selection JSON ID cell
    at Function.jsonID (index.es.js?5313:188)
    at eval (index.js?fc88:594)
    at Object../node_modules/prosemirror-tables/dist/index.js (chunk-vendors.js:3580)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (index.js?986d:7)
    at Object../node_modules/prosemirror-utils/dist/index.js (chunk-vendors.js:3604)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Module.eval (element-tiptap.esm.js?4ccc:1)

**Comment by SkyMonkya** [comment]
找到解决方案了,原因是引入了重复的不同版本的模块`prosemirror-tables`，解决方案：
方案1.将`node_modules/titap-extensions`文件夹下面的`node_modules`改下名字就可以了比如说改成`node_modules--`;
方案2.将`node_modules/titap-extensions/node_modules/prosemirror-tables`删除也可以。
总之不让第二个版本被引入即可

**Comment by HEART-max** [comment]
感谢，已经解决了！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Leecason/element-tiptap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月16日(星期五) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Leecason/element-tiptap] 引入：import { ElementTiptap } from "element-tiptap";后控制台报错：Duplicate use of selection JSON ID cell (#375)





 
找到解决方案了,原因是引入了重复的不同版本的模块prosemirror-tables，解决方案：
 方案1.将node_modules/titap-extensions文件夹下面的node_modules改下名字就可以了比如说改成node_modules--;
 方案2.将node_modules/titap-extensions/node_modules/prosemirror-tables删除也可以。
 总之不让第二个版本被引入即可

**Comment by DuShuais** [comment]
为什么我按照你的第二种方法删除了文件夹之后还是报错呀。
错误提示Failed to compile.
./node_modules/tiptap-extensions/node_modules/prosemirror-tables/dist/index.es.js
Module build failed: Error: ENOENT: no such file or directory, open 'F:\toutiao_admin\node_modules\tiptap-extensions\node_modules\prosemirror-tables\dist\index.es.js'
看到可以再回复一下嘛，打扰了

**Comment by suyu321** [comment]
没有titap-extensions目录怎么办啊




![Z2R(N N0WQ}BCJD$D~KO}ET](https://user-images.githubusercontent.com/84076398/144050312-d6b5e12c-843d-4c41-9e21-a949848609a7.png)
