### ISSUE TITLE
Editor is not visible due to console error

### ISSUE THREAD

**Issue by chlewicki** [Leecason/element-tiptap#39]
Hey,

After release 1.17.1, I started getting error:
`Error in nextTick: "TypeError: Cannot redefine property: isFullscreen"`

I have tiptap editor on two different pages and I'm using simple `vue transition` to switch between them. On initial page load editor is fully visible and functional, but it breaks while navigating to a different page with different editor (same component).

Structure for reference:

Project
|-- components
|   |-- ElementTipTap.vue
|-- views
|   |-- Page1.vue (imports ElementTipTap component)
|   |-- Page2.vue (imports ElementTipTap component)

**Comment by Leecason** [comment]
fixed in 1.17.2
