### ISSUE TITLE
Add element-ui to dependencies

### ISSUE THREAD

**Issue by Eguthrie3214** [Leecason/element-tiptap#391]
**Is your feature request related to a problem? Please describe.**
element ui is not installed as a dependency and needs to be added manually
**Describe the solution you'd like**
Not have to add this manually when adding element-tiptap

These dependencies were not found:

* element-ui/lib/button in ./node_modules/element-tiptap/lib/element-tiptap.esm.js
* element-ui/lib/checkbox in ./node_modules/element-tiptap/lib/element-tiptap.esm.js
* element-ui/lib/dialog in ./node_modules/element-tiptap/lib/element-tiptap.esm.js
* element-ui/lib/dropdown in ./node_modules/element-tiptap/lib/element-tiptap.esm.js
* element-ui/lib/dropdown-item in ./node_modules/element-tiptap/lib/element-tiptap.esm.js
* element-ui/lib/dropdown-menu in ./node_modules/element-tiptap/lib/element-tiptap.esm.js
* element-ui/lib/message-box in ./node_modules/element-tiptap/lib/element-tiptap.esm.js
* element-ui/lib/popover in ./node_modules/element-tiptap/lib/element-tiptap.esm.js
* element-ui/lib/tooltip in ./node_modules/element-tiptap/lib/element-tiptap.esm.js
* element-ui/lib/upload in ./node_modules/element-tiptap/lib/element-tiptap.esm.js

**Comment by Leecason** [comment]
ElementTiptap is a WYSIWYG for project with element-ui, so your project need install it manually
