### ISSUE TITLE
项目中用了ant-design-vue，该怎么用tiptap?

### ISSUE THREAD

**Issue by naix1024** [Leecason/element-tiptap#414]
不导入ElementUI的情况下还能使用tiptap吗？

如果有ant-design，再导入elementUI会不会产生冲突，变得很麻烦？

**Comment by Leecason** [comment]
这个是和 element-ui 配套使用的，暂时不支持 antd

**Comment by Leecason** [comment]
可以自行开发 tiptap + antd 哈
