### ISSUE TITLE
[feature-request] Quick option for setting disableInputRules and disablePasteRules

### ISSUE THREAD

**Issue by leo1200** [Leecason/element-tiptap#47]
The input and paste rules lead to annoying unexpected behavior.
So I suggest disabling them by default or adding a quick option to do so.

I for instance tried to paste LaTeX-Formulas but they were not displayed properly on the website. And it really took me a while to figure out, that the problem had to do something with the editor and that some parts of the formulas were misinterpreted to italian style ;)

**Comment by Leecason** [comment]
Hey, sorry for the delay
Can you describe how to reproduce it?

**Comment by leo1200** [comment]
After pasting
\[\sum_{\nu = 1}^{k + 1}\nu = \sum_{\nu = 1}^{k}\nu + k + 1 = \frac{k \bullet (k + 1)}{2} + k + 1 = \frac{(k + 1 + 1)(k + 1)}{2}\]
into the editor it displays
\[\sum{\nu = 1}^{k + 1}\nu = \sum{\nu = 1}^{k}\nu + k + 1 = \frac{k \bullet (k + 1)}{2} + k + 1 = \frac{(k + 1 + 1)(k + 1)}{2}\]
All _ or gone and some some parts of the text are in italian style.

**Comment by Leecason** [comment]
You can disable this by overwriting italic's pasteRules with temporarily

```js
import { OriginalItalic } from 'element-tiptap';

class Italic extends OriginalItalic {
  pasteRules () {
    return [];
  }
}

...

extensions: [
  new Italic(),
]
```
I'll think of a better way to solve it.

**Comment by leo1200** [comment]
Thanks 👍

**Comment by Leecason** [comment]
Now you can
```vue
<template>
  <el-tiptap :editor-properties="editorProperties"></el-tiptap>
</template>

<script>
..
  data () {
    return {
       editorProperties: {
          disablePasteRules: ['italic']
       }
    };
  }
..
</script>
```

detail: [editorPropperties](https://github.com/Leecason/element-tiptap#editorproperties) prop
