### ISSUE TITLE
 根据官网文档，vue3引入报错。

### ISSUE THREAD

**Issue by lipingshan** [Leecason/element-tiptap#480]
**Describe the bug**
- 环境 vue3（3.3.4）+ element-plus +element-tiptap
- 根据文档 [README_ZH.md](https://githubfast.com/Leecason/element-tiptap/blob/next/README_ZH.md),
尝试使用。
根本连demo都运行不了。
![image](https://github.com/Leecason/element-tiptap/assets/44489654/c0e16c9d-2b35-49b4-b82a-61b01d139eda)

**Comment by akronbook** [comment]
Still have the same issue when trying the basic example with Vue 3. I still get the getBoundingClientRect error. Any thoughts?
