### ISSUE TITLE
The formatting tooltip and dropdown menu small suggestions

### ISSUE THREAD

**Issue by eudoxyz** [Leecason/element-tiptap#5]
Maybe the "Heading" tooltip name is misleading here. I suggest "Formatting". I also suggest capitalizing all entry names in the dropdown menu.

![10-50-24](https://user-images.githubusercontent.com/10743071/73529864-b59b1e80-4417-11ea-8f3f-234ae33300c0.png)

**Comment by Leecason** [comment]
The button belongs to `Heading` extension, so I set "Heading". I will capitalize "paragraph", thx.

**Comment by Leecason** [comment]
I have capitalized 'Paragraph' in `Heading` dropdown.
