### ISSUE TITLE
How to display buttons in either menu bar or bubble menu but not both?

### ISSUE THREAD

**Issue by shadrachtuck** [Leecason/element-tiptap#53]
Hello I'm not sure how to exclude extensions from the top menu if I want to still use them in the bubble menu and vice-versa. Let me know, thank you!

**Comment by Leecason** [comment]
Now all extension will render in the menubar. If you want to render in the bubble menu, you need to pass `bubble: true` to extension. But for the moment, there is no config to hide it from the menubar and only appear in the bubble. It will be a new feature.

**Comment by shadrachtuck** [comment]
Lee, thank you for your the response, looking forward to the feature update.
