### ISSUE TITLE
Feature request: view/edit HTML source code

### ISSUE THREAD

**Issue by eudoxyz** [Leecason/element-tiptap#6]
Maybe?

**Comment by Leecason** [comment]
```html
<el-tiptap v-model="content" />
```

You can change `content` and the editor will react.

**Comment by eudoxyz** [comment]
An extension with an appropriate menu button would be nice.

**Comment by Leecason** [comment]
I don't understand the usage scenarios. Could you tell me more details about this ?

**Comment by Leecason** [comment]
A new `Preview` extension for preview
see: https://leecason.github.io/element-tiptap/preview
