### ISSUE TITLE
Question: How do custom extensions pass props to their associated component?

### ISSUE THREAD

**Issue by shadrachtuck** [Leecason/element-tiptap#60]
Hello, I've had a hard time understanding the relationship between the custom extensions and their components. Is there perhaps a way you could provide a diagram with all the things you've added on top of TipTap with and how data is being passed back and forth? I've read both TipTap and Prosemirror documentation and I can't seem to understand how it all comes together.

**Comment by Leecason** [comment]
[Tiptap initNodeViews](https://github.com/scrumpy/tiptap/blob/3e7e351f939eb279d7b061089d1cdd9479debf1c/packages/tiptap/src/Editor.js#L299) will collect the node views you define, instantiate them then pass to [Prosemirror EditorProps.nodeViews](https://prosemirror.net/docs/ref/#view.EditorProps.nodeViews)

**Comment by shadrachtuck** [comment]
@Leecason Thank you, can you post an example or some kind of visual aid?

**Comment by Leecason** [comment]
you can check this example https://codesandbox.io/s/template-button-ctlmm
