### ISSUE TITLE
大佬，如何实现图片空间。。

### ISSUE THREAD

**Issue by yuanxiongwei** [Leecason/element-tiptap#61]
终于看到一个一眼就心动的编辑器了，太棒了。
插入图片是否可以设计一个服务器得图片空间，从图片空间中得图片选择进行插入。同时页能批量上传图片到图片空间。
希望能有这样的一个组件或者指一条明路。

**Comment by nszm** [comment]
你可以自己写个扩展

**Comment by Leecason** [comment]
谢谢~
图片这边的功能暂时有点简陋，还在想怎么扩展
目前暂时只支持两个配置 https://github.com/Leecason/element-tiptap/issues/49
你可以自定义 `uploadRequest` 操作
```js
new Image({
  uploadRequest: function (file) { // 原生 File 对象
     ... // 处理你的上传逻辑，可以上传到自己的服务器什么的（需要写异步代码）
     return url; // 之后返回上传成功后的 url 就可以了
  },
});
```
目前只支持一张图片的上传，多张还没做。
如果要设计素材库这样的功能的话，可能需要自己写扩展了
1. 改写一下 `Image` 的 `menuBtnView`，替换为你自己的素材库组件
2. 既然是你自己的组件了就可以为所欲为了，最后手写一下[插入图片](https://github.com/Leecason/element-tiptap/blob/master/src/components/MenuCommands/Image/InsertImageCommandButton.vue#L113)的逻辑就好了

**Comment by yuanxiongwei** [comment]
感谢，研究一下先。还是希望官方能提供方案。呵呵呵

**Comment by yuanxiongwei** [comment]
我已经有一个图片库的组件了。用于其他地方。我想知道能不能简单的拿过来用。我现在的思路需求如下：
1、能自定义点击按钮事件，可以让我传入参数给我的图片库组件。
2、图片库组件操作完后，会有一个回传值事件，希望编辑器能提供插入的方法。

**Comment by yuanxiongwei** [comment]
实力有限，研究一天，没有弄出来。希望能获得帮助

**Comment by nszm** [comment]
> 实力有限，研究一天，没有弄出来。希望能获得帮助

我之前是这样做的
` 
 menuBtnView({ isActive, commands, focus, editor }) {
    return {
      component: ImageMenuButton,
      componentEvents: {
        click: (url) => {
          commands.image({'src':url})
          // you can do somethings when button clicked
        }
      }
    }
  }
`

**Comment by yuanxiongwei** [comment]
@nszm  
又捣鼓了一上午我闹明白了这一步。我现在有几个问题需要解决。
1.、这样做出来按钮是自定义的。如何保持一样的菜单效果。
2、如何给这个自定义的组件设置参数。给到自定义的操作逻辑使用。
比如在 new customeImage({参数1：‘’，参数2：‘’})

**Comment by Leecason** [comment]
```js
menuBtnView({ isActive, commands }) {
    return {
      component: ImageMenuButton,
      componentProps: {
        // 这里可以传入自定义组件的 props
        active: isActive,
      },
      componentEvents: {
        ensure: (url) => {
          commands.image({ src: url })
        }
      }
    }
  }
```

编辑器只依赖最终上传完成的 url 然后插入就行了，中间上传的过程可能性比较多，不太好做到暴露一个上传接口就能满足所有的场景，比如可能会打开一个 iframe 在里面做上传，使用自定义的组件的话，扩展性更强。

**Comment by yuanxiongwei** [comment]
@Leecason  非常感谢。顺利解决问题。在大佬的帮助下，让我这个前端菜鸟爱上了这个编辑器。

**Comment by yuanxiongwei** [comment]
分享一下我的实现：
建立一个自定义组件文件夹
比如：extensions
我的组件是image，在/extensions/image目录下建image.vue和index.js文件

index.js代码
`
import { Image as ImageCommandButton } from "element-tiptap";
import CustomImageMenuButton from "./image";

export default class CustomImage extends ImageCommandButton {
    menuBtnView({ editor }) {
        const options = this.options.options;
        return {
            component: CustomImageMenuButton,
            componentProps: {
                options: options
            },
            componentEvents: {
                insert: (files) => {
                    for (var i = 0; i < files.length; i++) {
                        editor.commands.image({ src: files[i].path });
                    }
                    console.log('insert', files)
                }
            }
        };
    }
}

`

image.vue代码如下：
`
<template>
    <div>
        <div class="el-tooltip el-tiptap-editor__command-button el-popover__reference" aria-describedby="el-popover-8779" tabindex="0" @click="onClick">
            <svg aria-hidden="true" width="16" height="16" viewBox="0 0 512 512" focusable="false" class="fa-icon">
                <g>
                    <path d="M464 448h-416c-26.5 0-48-21.5-48-48v-288c0-26.5 21.5-48 48-48h416c26.5 0 48 21.5 48 48v288c0 26.5-21.5 48-48 48zM112 120c-30.9 0-56 25.1-56 56s25.1 56 56 56 56-25.1 56-56-25.1-56-56-56zM64 384h384v-112l-87.5-87.5c-4.7-4.7-12.3-4.7-17 0l-135.5 135.5-55.5-55.5c-4.7-4.7-12.3-4.7-17 0l-71.5 71.5v48z"></path>
                </g>
            </svg>
        </div>
        <el-dialog title="图片空间" :visible.sync="pictureVisible" :close-on-click-modal="false" width="60%">
            <photos ref="photos" :limit="pictureLimit" @close="hiddenPictureVisible" @insert="handleInsertPicture" :name="pictureName" :data="pictureData"></photos>
        </el-dialog>
    </div>
</template>

<script>
    export default {
        name: "ImageMenuButton",
        props: ['options'],
        data() {
            return {
                pictureName: '',
                pictureData: [],
                pictureLimit: 20,
                pictureVisible: false
            }
        },
        methods: {
            onClick() {
                this.$nextTick(() => {
                    this.pictureData = []
                    this.pictureVisible = true
                })
            },
            hiddenPictureVisible() {
                this.pictureVisible = false
            },
            handleInsertPicture(from, files) {
                this.$emit("insert", files)
                this.pictureVisible = false
            }
        }
    };
</script>

`

**Comment by Leecason** [comment]
贴代码的时候最好可以提前 format 一下，不然别人看起来有些吃力
这个 issue 我先关了哦
