### ISSUE TITLE
no css

### ISSUE THREAD

**Issue by hudingwen** [Leecason/element-tiptap#67]
![image](https://user-images.githubusercontent.com/36782822/81249369-004cb800-9051-11ea-8089-7c638dbcb706.png)
![image](https://user-images.githubusercontent.com/36782822/81249424-1e1a1d00-9051-11ea-98aa-04a19416cdf7.png)

why don't hava css ?

**Comment by Leecason** [comment]
make sure you import the style files

```js
import 'element-ui/lib/theme-chalk/index.css';
import 'element-tiptap/lib/index.css';
```

**Comment by hudingwen** [comment]
I used it
I placed in main.js

**Comment by hudingwen** [comment]
but still no effect

**Comment by Leecason** [comment]
can you provide codesandbox to reproduce this problem?

**Comment by hudingwen** [comment]
> can you provide codesandbox to reproduce this problem?

thanks.I succeed.i used a demo to finish
