### ISSUE TITLE
Feature request: disable default content styles

### ISSUE THREAD

**Issue by eudoxyz** [Leecason/element-tiptap#7]
Right now I need to overwrite default editor styles in order to apply my global styles. Would be nice if the editor could optionally inherit these styles for its content alone. Menu-bar is fine, I wouldn't want to change that.

**Comment by Leecason** [comment]
I haven't considered this yet. Maybe I will extract the rich text css file, if need, user can introduce style file.

**Comment by Leecason** [comment]
now element-tiptap content styles are below `el-tiptap-editor__content` class, you can use custom class for your content.
