### ISSUE TITLE
Adding own action button

### ISSUE THREAD

**Issue by tbhaxor** [Leecason/element-tiptap#71]
I want implement a template button, that has variables like `{{first_name}}`, whenever the user clicks on that button, it adds the `{{first_name}}` at current cursor position

**Comment by Leecason** [comment]
sry for the delay, hope helpful for you: [template button example](https://codesandbox.io/s/template-button-ctlmm)

**Comment by Elrinth** [comment]
Hi! I'd like to create a button which creates a <button>test</button> html when pushed, how do I do this?
