### ISSUE TITLE
[Vue warn]: Error in mounted hook: "RangeError: Schema is missing its top node type ('doc')

### ISSUE THREAD

**Issue by outman** [Leecason/element-tiptap#72]
`
 [Vue warn]: Error in mounted hook: "RangeError: Schema is missing its top node type ('doc')"

found in

---> <ElTiptap>
       <ElCol>
         <ElRow>
           <ElFormItem> at packages/form/src/form-item.vue
             <ElForm> at packages/form/src/form.vue
               <ElCard> at packages/card/src/main.vue
                 <Root>
`
相关依赖版本
`
        "element-tiptap": "^1.20.0",
        "element-ui": "^2.13.1",
        "vue": "^2.6.11"
`

**Comment by Leecason** [comment]
For the editor, `Doc`、`Text`、`Paragraph` are the necessary extensions.
I will improve the docs.
