### ISSUE TITLE
插入图片输出的HTML标签竟然是image 

### ISSUE THREAD

**Issue by yuanxiongwei** [Leecason/element-tiptap#79]
插入图片输出的HTML标签竟然是image ,请问这里要怎么处理。标准的html标签应该是img才对呢

**Comment by czy27** [comment]
怎么解决的呢大佬

**Comment by Leecason** [comment]
> 怎么解决的呢大佬

https://github.com/Leecason/element-tiptap/commit/627c5aba376df82a699948709304a1f503aac1e7
