### ISSUE TITLE
let『Title』 to be a independent module，add divider and placeholder

### ISSUE THREAD

**Issue by Jinkeycode** [Leecason/element-tiptap#83]
Now，we need to open Title function like
```javascript
new Doc({ title: true })
```
But I think it is more appropriate for becoming a independent module, and import by
```javascript
new Title({ divider: true, placeholder: 'Write title here' })
```
Finally, the effect will be
![](https://user-images.githubusercontent.com/12148377/82531859-b8f71900-9b72-11ea-8626-71596a245c12.png)

**Comment by Leecason** [comment]
If `Title` is a independent extension, I cannot specify the `Doc` schema content when instantiate(`Doc` must instantiate first), at this time I dont know if there will be a `Title` extension.

https://github.com/Leecason/element-tiptap/blob/master/src/extensions/doc.ts#L14

**Comment by Jinkeycode** [comment]
OK! So should we add properties `divider ` and `placeholder` to Doc extension ?

**Comment by Leecason** [comment]
usage:

```js
new Doc({
  title: true,
}),
new Title({
  placeholder: 'some text',
  class: 'divider', // or others
})
```

add divider style
```css
.divider {
  border-bottom: 1px solid #000;
}
```

**Comment by Jinkeycode** [comment]
Cool!
