### ISSUE TITLE
视频插入不了

### ISSUE THREAD

**Issue by qingpengtan** [Leecason/element-tiptap#85]
视频插入的时候提示这个是为什么？

vue.runtime.esm.js:619 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> Anonymous>
       EditorContent>
         ElTiptap>

**Comment by qingpengtan** [comment]
版本 1.21.0

**Comment by Leecason** [comment]
https://github.com/vuejs/vue-cli/issues/2754

**Comment by qingpengtan** [comment]
3q very much!大佬有没有打赏码，给大佬端杯茶

**Comment by Leecason** [comment]
不客气
