### ISSUE TITLE
[Bug]Table create and delete problem

### ISSUE THREAD

**Issue by Jinkeycode** [Leecason/element-tiptap#86]
# For Creating
I selected 6 * 2 table in menubar, but got 2 * 6 table in content

![image](https://user-images.githubusercontent.com/12148377/82558755-f1155080-9ba0-11ea-9fee-6dedf019f390.png)
![image](https://user-images.githubusercontent.com/12148377/82558767-f6729b00-9ba0-11ea-8090-2cd1af0291e7.png)

# For Deleting
No matter I select all the table and press 『Delete』to delete all the table，or focu on a table cell and press 『Delete』, I can't delete table、 table row or table column.

**Comment by Leecason** [comment]
I think should add bubble menu for table for your `For Deleting`
