### ISSUE TITLE
Insert link not working

### ISSUE THREAD

**Issue by FurtakM** [Leecason/element-tiptap#9]
Hi, I have problem with "apply link". Pasted link did not show up after insert.
[Demo](https://i.gyazo.com/ed059efcdf6279258b36a260eb8b3805.gif)

Tested on Firefox and Chromium.

**Comment by Leecason** [comment]
To add a link you need a selection, `Insert link` means `add a link to the text`, not `insert a text with link`. Maybe I should rename it to `Add link`?

**Comment by FurtakM** [comment]
Yeah, you are right. Anyway, there should be option for **Insert Link** itself.

`<a :href='myurl'>{{ myText }}</a>`

But i think it's unreachable at this stage: [Issue 373](https://github.com/scrumpy/tiptap/issues/373)

**Comment by Leecason** [comment]
I'm going to update the i18n text first, and then I will do this.

**Comment by Leecason** [comment]
I add a bubble menu for link in latest release
