### ISSUE TITLE
Bubble menu doesn't appear when using keyboard select all shortcut

### ISSUE THREAD

**Issue by justanotherco** [Leecason/element-tiptap#97]
Hi again,

If you press cmd + A to select all the text, the bubble menu doesn't appear here:

https://leecason.github.io/element-tiptap/bubble_menu

But it does here:

https://tiptap.scrumpy.io/menu-bubble

Is this a bug in Element tiptap?

Thanks.

**Comment by Leecason** [comment]
I've overwritten the code of appearing bubble menu, that is different from tiptap's, I will try to improve this, thank you.
